### ISSUE TITLE
[REZULTATE] Returnare indici din highschool API

### ISSUE THREAD

**Issue by sturzamihai** [nevexo-technologies/real#11]
Mod calculare indici:

Oportunități:

> Indicele de oportunități al unui liceu este calculat prin media aritmetică a următoarelor variabile: E10 - E16, P05 - P07, T10 - T12. 

    
Resurse: 

> Indicele de resurse al unui liceu este calculat prin media aritmetică a următoarelor variabile: P08, P09, E20, E22 - E25B, plus o variabilă auxiliară pe care o vom nota cu A01.

 A01 este calculată pe baza a 25 de elemente distincte luate din variabilele E19, E21, I07, I08, I14 împărțită la I56 (pentru a afla numărul mediu de calculatoare din sălile de informatică pentru fiecare elev), I21 - I27. Existența fiecărui element adaugă 0.4 la nota finală.

Comunitate de elevi:

> Indicele de comunitate de elevi al unui liceu este calculat prin media aritmetică a următoarelor variabile: E32, E33*, E38*, E39, E40, E41*, E43, P12, P19, P20*, P22, T20*

* Pentru aceste variabile, nota finală este reprezentată de procentul de respondenți care nu au menționat existența unui comportament nociv din partea elevilor (ex: pentru variabila E33, dacă 90% dintre respondenți nu au menționat comunitatea de elevi ca factor de stres, atunci nota ce se va lua în considerare pentru această variabilă este 9)

Comunitate de profesori:

> Indicele de comunitate de profesori al unui liceu este calculat prin media aritmetică a următoarelor variabile: E26, E27, E28, E29, E30, E31, E32, E33*, E34, E35, E37, E38*, E41*, P10, P11, P18, P20*, T16, T17, T19, T20*

* Pentru aceste variabile, nota finală este reprezentată de procentul de respondenți care nu au menționat existența unui comportament nociv din partea profesorilor (ex: pentru variabila E33, dacă 90% dintre respondenți nu au menționat comunitatea de profesori ca factor de stres, atunci nota ce se va lua în considerare pentru această variabilă este 9)

Indice de incluzivitate:

> Indicele de incluzivitate al unui liceu este calculat prin media aritmetică a următoarelor variabile: E13, E14, E15, E16, E21, E34, E35, E38*, E39, E41, P10, P11, T19 și o variabilă auxiliară pe care o vom nota cu A02.
* A02 este calculată prin media aritmetică a procentelor exprimate prin variabilele I69 - I71.

_Originally posted by @sturzamihai in https://github.com/nevexo-technologies/real/issues/8#issuecomment-1324900855_

**Comment by stefanRoberto** [comment]
+ Conditie validare min 10 elevi si 1 prof, altfel Not enough data

**Comment by stefanRoberto** [comment]
Helper pt extragerea indicilor

**Comment by sturzamihai** [comment]
> Helper pt extragerea indicilor

Parametrii sa fie urmatorii:
- `data`: lista ce contine toate formularele completate pentru **un singur** liceu

Output-ul trebuie sa fie de tip `IHsMetrics`. In cazul in care functie a async, sa returneze `Promise<IHsMetrics>`

```ts
interface IHsMetrics {
  opportunities: number,
  resources: number,
  studentCommunity: number,
  teacherCommunity: number,
  inclusivity: number
}

function getHsMetrics(data: (Elev | Profesor | Parinte)[]) : IHsMetrics {
  // ... 

  return {
  ...
  }
}
```
